name: parking-research
channels:
  - pytorch
  - comet_ml
  - conda-forge
  - defaults
dependencies:
  - transformers
  - pytorch
  - torchvision
  - matplotlib
  - ipywidgets
  - opencv
  - ipympl
  - ipyevents
  - pandas
  - albumentations
  - comet_ml
  - inquirer